### ISSUE TITLE
Are you interested in merging back into my project?

### ISSUE THREAD

**Issue by sloansparger** [b4dnewz/wordpress-development#1]
I know I don't have a license, so you are free to take my code as you please, but I wanted to know if you were interested in making a PR back into my original repo (https://github.com/sloansparger/webpack-wordpress) and combining efforts? I'd love to add you as a contributor/author of the project.

**Comment by sloansparger** [comment]
I'll also add that there's already quiet a few people using my project, a couple of Wordpress shops are using it for development actively, so you would get the added benefit of your efforts reaching active developers.

**Comment by b4dnewz** [comment]
Yes man for sure, but I must I have to anticipate that however I changed a
lot in the code, so it will be a massive PR, that's the main reason why I
choose to not use the forked version but to create a new one.

Do you think is a good idea? I've to say since the default theme wosn't
exactly what I was expecting I'm (still doing it) replacing with a "blank
default theme" based on extracts from twenty**een themes.

Does it fit your needs? This is just a warning because I don't want you to
see your project completely changed after that, but there is to be said few
things wan't working and now there are and I also completed some of the
tasks you've added as todo for example "have page refresh when php file is
changed, not just sass and js" which I think is kind of the main goal of
all this.


Let me know, many thanks.

**Comment by b4dnewz** [comment]
Closed for inactivity.
